In [610]:
## From here we're going to learnt about numpy library in python . 

In [611]:
import numpy as np

In [612]:
numpyArr = np.array([(23,34,564,57,12)],np.int64)

In [613]:
print(numpyArr[0,3]) ## Here , we prints the first row and the 4th column 
                    ## This is an one dimn arr. 

57


In [614]:
numpyArr.shape

(1, 5)

In [615]:
numpyArr.size

5

## Array Creation Methods by using Numpy !!

In [616]:
myArr = np.array([[12,234,45], ["Kashish" , "Hirak" , "Sanu"]]) ## This is an 2-D arr. It has 2 rows and 3 columns 

In [617]:
print(myArr[1,0] + " meets " + myArr[1,1])

Kashish meets Hirak


In [618]:
myArr.shape

(2, 3)

In [619]:
zerothArr = np.zeros([3,4])

In [620]:
print(zerothArr)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [621]:
equispaceArr = np.linspace(0,100,10) 

In [622]:
print(equispaceArr)

[  0.          11.11111111  22.22222222  33.33333333  44.44444444
  55.55555556  66.66666667  77.77777778  88.88888889 100.        ]


In [623]:
print(equispaceArr[3])

33.33333333333333


## Empty Method 

In [624]:
## This method is used to made an array of given shape and size , the no of enteries are the random values. 

In [625]:
emptyArr = np.empty((3,3),dtype=int)

In [626]:
print(emptyArr)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## Linspace Method 

In [627]:
## This method is usually used to made an arr of enteries , in a given interval range and with an fixed constant space between them . 

In [628]:
## Parameters 
## Main Params 1. start-> Start interval 2. end -> End Interval 3. num =This params defines the total no of enteries.  
## 4. restep= This is used to to return (samples , space b/w enteries ) if True . 
## as default False.  

In [629]:
myLinspaceArr = np.linspace(21,45 ,5, retstep=True)

In [630]:
print(myLinspaceArr)

(array([21., 27., 33., 39., 45.]), 6.0)


In [631]:
## Lets makes an identity matrix with the help of the method named identity . 

In [632]:
ideMatrix = np.identity(5)

In [633]:
print(ideMatrix)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [634]:
## Arange method -- This method is mainly used to makes an array with the enteries (from 0 to n-1)

In [635]:
whole_num = np.arange(100)
print(whole_num)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [636]:
## Reshape method --> It is generally used to creates an matrix with customize rows and columns but with the fixed elements of the exisisting array and also it is the temporary 
                    ## copy made which doesn't affects the orginal itself until you assigned into it. 

reshapeMatrix = whole_num.reshape(4,25)
print(reshapeMatrix) 

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]
 [50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73
  74]
 [75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97 98
  99]]


In [637]:
## The key difference between reshape and resize methods 

# reshape -> This method is used to temporarily change the shape of the array that's why the existing array itself is doesn't affected , until you assigned to the existing array itself to change it into an new one . 
# resize -> This method is changes the size of the array permenantely , means the array itself changes into an new rows and columns . 

n = np.arange(20)
# n = n.reshape(5,4) ## Here, the existing arr changes as you assigned it into an existing one itself. 
# n.resize(4,5) 
reshape_arr = n.reshape(5,4) ## Here, it doesn't changes as it is assigned into an new var. 
print(f"I am the reshape one  {reshape_arr}\n")
print(f"I am the existing array : {n}")

I am the reshape one  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]

I am the existing array : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [638]:
## Let's makes an 1-D array , the method for making the 1-D array is .ravel() .
num_arr = np.identity(5)
oned_arr = num_arr.ravel()
print(f"The array is : {oned_arr} and it's shape is : {oned_arr.shape}")

The array is : [1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0.
 1.] and it's shape is : (25,)


In [639]:
equiArr = np.empty((3,2))
oned_arr_2 = equiArr.ravel()
print(equiArr.shape)
print(oned_arr_2)
print(oned_arr_2.shape)

(3, 2)
[ 1.   3.8  6.6  9.4 12.2 15. ]
(6,)


In [640]:
## Here, going to know about axis . mainly , 1D and 2D axis . 

## In 1D we have only one axis . So that should be known as axis 0.
## In 2D we have only two axis, So that should be known as axis 0 and axis 1. 
## In conclusion #
# 1D - 0 axis -> It's the sum of all the enteries in one row of the 1D array , In one d arr the axis 0 taken as the horizantal line . 

# 2D - 0 axis-> Sum of all the enteries of the columns in 2D array ,and  1 axis -> Sum of all the enteries of the rows in 2D array , In 2d arr
##              the vertical line taken as axis 0 whereas , the horizantal line taken as axis 1. 

In [641]:
arr = np.arange(6)  ## 1 D array
two_D_arr = arr.reshape(2,3) ## 2 D array. 
print(arr)
print(f"The no of dimensions of 1-d array is : {arr.ndim}")
print(arr.sum(axis=0))
print(two_D_arr)
print(two_D_arr.sum(axis=1))



[0 1 2 3 4 5]
The no of dimensions of 1-d array is : 1
15
[[0 1 2]
 [3 4 5]]
[ 3 12]


In [642]:
## Transposing the 2D array . 
t_arr = two_D_arr.T
print(t_arr)
print(t_arr.shape)
print(f"The no of dimensions of two-d array is: {t_arr.ndim}")
print(f"The max value of two-d array is: {two_D_arr.argmax()}")


[[0 3]
 [1 4]
 [2 5]]
(3, 2)
The no of dimensions of two-d array is: 2
The max value of two-d array is: 5


In [643]:
## argmax , argmin , argsort are used to determine the max , min values in the arr and sort out the array too. 
np_arr = [320 , 98 , 132 , 68]
np_arr = np.array(np_arr)
print(np_arr)
print(np_arr.argmin())
print(np_arr.argmax())
print(np_arr.argsort())

[320  98 132  68]
3
0
[3 1 2 0]


In [644]:
## 2d array 
arr_new = np.linspace(20,40,6 )
two_d_arr_2 = arr_new.reshape(3,2)
# print(two_d_arr_2)
two_d_arr_2[1,0] = 234
print(two_d_arr_2)
# print(two_d_arr_2.argmax(axis=0))

print(two_d_arr_2.argsort(axis=1))
# print(two_d_arr_2.argsort(axis=0))

[[ 20.  24.]
 [234.  32.]
 [ 36.  40.]]
[[0 1]
 [1 0]
 [0 1]]


In [645]:
## Addition of matrices 
arr_1 = np.arange(6)
arr_1 = arr_1.reshape(3,2)
arr_2 = np.linspace(1,10,6)
arr_2 = arr_2.reshape(3,2)


add_matrix = arr_1 + arr_2
print(add_matrix)

[[ 1.   3.8]
 [ 6.6  9.4]
 [12.2 15. ]]


In [646]:
## We can apply all the matrices operations in the numpy arr. 

num_py_arr = np.arange(9)
num_py_arr = num_py_arr.reshape(3,3)
# print(num_py_arr)

ide_arr = np.identity(3)
# print(ide_arr)

numpy_arr_sum = num_py_arr + ide_arr
print(f"This is the sum of both the arrays: \n{numpy_arr_sum}")


numpy_arr_sum = num_py_arr * ide_arr
print(f"This is the multiplication of both the arrays: \n{numpy_arr_sum}")



This is the sum of both the arrays: 
[[1. 1. 2.]
 [3. 5. 5.]
 [6. 7. 9.]]
This is the multiplication of both the arrays: 
[[0. 0. 0.]
 [0. 4. 0.]
 [0. 0. 8.]]


In [647]:
num_py_arr = np.sqrt(num_py_arr)
print(num_py_arr)

[[0.         1.         1.41421356]
 [1.73205081 2.         2.23606798]
 [2.44948974 2.64575131 2.82842712]]


In [648]:
## We can also use .where() method which considered to follow some conditions

ide_arr[1,0] = 231
print(ide_arr)
print(np.where(ide_arr>1)) 

## .where() -> Returns an tuple of the numpy_arr of the elements of rows and columns by follows some certain conditions. 

[[  1.   0.   0.]
 [231.   1.   0.]
 [  0.   0.   1.]]
(array([1], dtype=int64), array([0], dtype=int64))


In [649]:
# np.count_nonzero(ide_arr) ## It returns how many non-zero elements are present in the arr. 
print(ide_arr)
np.nonzero(ide_arr)

[[  1.   0.   0.]
 [231.   1.   0.]
 [  0.   0.   1.]]


(array([0, 1, 1, 2], dtype=int64), array([0, 0, 1, 2], dtype=int64))

In [650]:
## Python_arr v/s numpy_arr

import sys 

numpyArr = np.linspace(10,40,3)
pyArr = [23,12,34]

numpy_arr_bitsize = numpyArr.itemsize * numpyArr.size
py_arr_bitsize = sys.getsizeof(1) * len(pyArr)

print(f"The size of numpy Arr is : {numpy_arr_bitsize}") 
print(f"numpyarr size: {numpyArr.size}")
print(f"numpyarr itemsize: {numpyArr.itemsize}")
print(f"The size of py Arr is : {py_arr_bitsize}")

## That's the reason why we use numpyArr just see the difference. 

The size of numpy Arr is : 24
numpyarr size: 3
numpyarr itemsize: 8
The size of py Arr is : 84
